routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('welcome');
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' =>['auth','role:superadmin|ppc']],function(){
    Route::resource('user', 'mUserController');
    Route::resource('md', 'mManufactureDrawingController');

    Route::get('md_wp/wip/',[
        'as' => 'md_wip.wip',
        'uses' => 'mManufactureDrawingController@work_in_progress' 
    ]);

    Route::get('md_rl/rel',[
        'as' => 'md_rel.rel',
        'uses' => 'mManufactureDrawingController@released' 
    ]);

    Route::resource('is', 'mInspectionSheetController');

    Route::get('is_wp/wip',[
        'as' => 'is.wip',
        'uses' => 'mInspectionSheetController@work_in_progress' 
    ]);

    Route::get('is_rl/rel',[
        'as' => 'is.rel',
        'uses' => 'mInspectionSheetController@released' 
    ]);

    Route::resource('division', 'mDivisionController');
    Route::resource('position', 'mPositionController');
});

resources/views/master/position/_form.blade.php
<div class="row p-t-20">
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('position_code') ? 'has-error': '' }} ">
            {!! Form::label('position_code', 'Position Code', ['class'=>'form-label']) !!}
            {!! Form::text('position_code', null, ['class'=>'form-control']) !!} 
            {!! $errors->first('position_code', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group{{ $errors->has('position_name') ? 'has-error': '' }} ">
            {!! Form::label('position_name', 'Position Name', ['class'=>'form-label']) !!}
            {!! Form::text('position_name', null, ['class'=>'form-control']) !!} 
            {!! $errors->first('position_name', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
</div>

{!! Form::submit ('Simpan',['class'=>'btn btn-primary m-b-10 m-l-5']) !!}

resources/views/master/position/create.blade.php
@extends('adminlte::page')

@section('title', 'Position - Manufacturing 4.0')

@section('content_header')
    <h1>Position</h1>
@stop

@section('content')
<div class="right_col" role="main">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-6 align-self-center">
        <h4 class="c-grey-900 mT-10 mB-30">Management Position</h4> </div>
        <div class="col-md-6 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Master Data</li>
                <li class="breadcrumb-item">Partner</li>
                <li class="breadcrumb-item"><a href="{{ route('position.index') }}">Position</a></li>
                <li class="breadcrumb-item active">Create</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->

    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">
            {!! Form::open(['url' => route('position.store'),
                'method' => 'post' , 'id' => 'form_validation']) !!}
                @include('master.position._form')
            {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<!-- validator -->
<script src="{{ asset('gentelella/vendors/validator/validator.js') }}"></script>
@endsection

resources/views/master/position/edit.blade.php
@extends('adminlte::page')

@section('title', 'Position - Manufacturing 4.0')

@section('content_header')
    <h1>Position</h1>
@stop

@section('content')
<div class="right_col" role="main">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-6 align-self-center">
        <h4 class="c-grey-900 mT-10 mB-30">Management Position</h4> </div>
        <div class="col-md-6 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Master Position</li>
                <li class="breadcrumb-item">Partner</li>
                <li class="breadcrumb-item"><a href="{{ route('position.index') }}">Position</a></li>
                <li class="breadcrumb-item active">Edit</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->

    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">
            {!! Form::model($position, ['url' => route('position.update', $position->id),
                'method' => 'put' , 'id' => 'form_validation']) !!}
                @include('master.position._form')
            {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<!-- validator -->
<script src="{{ asset('gentelella/vendors/validator/validator.js') }}"></script>
@endsection

resources/views/master/position/index.blade.php
@extends('adminlte::page')

@section('title', 'Position - Manufacturing 4.0')

@section('content_header')
    <h1>Position</h1>
@stop

@section('content')
<div class="right_col" role="main">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-6 align-self-center">
        <h4 class="c-grey-900 mT-10 mB-30">Management Position</h4> </div>
        <div class="col-md-6 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">PPC</li>
                <li class="breadcrumb-item active">Position</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    
    @if(session()->has('flash_notification.message'))
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="body">
                @if(session()->get('flash_notification.level') == 'danger')
                <div style="background-color:red" class="alert alert-{{ session()->get('flash_notification.level') }} alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong><font color="white">{!! session()->get('flash_notification.message') !!}</font></strong>
                </div>
                @else
                <div class="alert alert-{{ session()->get('flash_notification.level') }} alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong><font color="white">{!! session()->get('flash_notification.message') !!}</font></strong>
                </div>
                @endif
            </div>
        </div>
    </div>
    @endif

    <div class="row">
        <div class="col-md-12">
            <div class="card card-default color-palette-box">
                <div class="card-body">
                    <div class="table-responsive">
                        {!! $dataTable->table(['class' => 'display nowrap table table-hover table-striped', 'width' => '100%']) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    {!! $dataTable->scripts() !!}
    <script> console.log('Hi!'); </script>
@stop