routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('welcome');
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' =>['auth','role:superadmin|ppc']],function(){
    Route::resource('user', 'mUserController');
    Route::resource('md', 'mManufactureDrawingController');

    Route::get('md_wp/wip/',[
        'as' => 'md_wip.wip',
        'uses' => 'mManufactureDrawingController@work_in_progress' 
    ]);

    Route::get('md_rl/rel',[
        'as' => 'md_rel.rel',
        'uses' => 'mManufactureDrawingController@released' 
    ]);

    Route::resource('is', 'mInspectionSheetController');

    Route::get('is_wp/wip',[
        'as' => 'is.wip',
        'uses' => 'mInspectionSheetController@work_in_progress' 
    ]);

    Route::get('is_rl/rel',[
        'as' => 'is.rel',
        'uses' => 'mInspectionSheetController@released' 
    ]);

    Route::resource('division', 'mDivisionController');
    Route::resource('position', 'mPositionController');
});

resources/views/master/division/_form.blade.php
<div class="row p-t-20">
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('division_code') ? 'has-error': '' }} ">
            {!! Form::label('division_code', 'Division Code', ['class'=>'form-label']) !!}
            {!! Form::text('division_code', null, ['class'=>'form-control']) !!} 
            {!! $errors->first('division_code', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group{{ $errors->has('division_name') ? 'has-error': '' }} ">
            {!! Form::label('division_name', 'Division Name', ['class'=>'form-label']) !!}
            {!! Form::text('division_name', null, ['class'=>'form-control']) !!} 
            {!! $errors->first('division_name', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
</div>

{!! Form::submit ('Simpan',['class'=>'btn btn-primary m-b-10 m-l-5']) !!}

resources/views/master/division/create.blade.php
@extends('adminlte::page')

@section('title', 'Division - Manufacturing 4.0')

@section('content_header')
    <h1>Division</h1>
@stop

@section('content')
<div class="right_col" role="main">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-6 align-self-center">
        <h4 class="c-grey-900 mT-10 mB-30">Management Division</h4> </div>
        <div class="col-md-6 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Master Data</li>
                <li class="breadcrumb-item">Partner</li>
                <li class="breadcrumb-item"><a href="{{ route('division.index') }}">Division</a></li>
                <li class="breadcrumb-item active">Create</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->

    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">
            {!! Form::open(['url' => route('division.store'),
                'method' => 'post' , 'id' => 'form_validation']) !!}
                @include('master.division._form')
            {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<!-- validator -->
<script src="{{ asset('gentelella/vendors/validator/validator.js') }}"></script>
@endsection

resources/views/master/division/edit.blade.php
@extends('adminlte::page')

@section('title', 'Division - Manufacturing 4.0')

@section('content_header')
    <h1>Division</h1>
@stop

@section('content')
<div class="right_col" role="main">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-6 align-self-center">
        <h4 class="c-grey-900 mT-10 mB-30">Management Division</h4> </div>
        <div class="col-md-6 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Master Division</li>
                <li class="breadcrumb-item">Partner</li>
                <li class="breadcrumb-item"><a href="{{ route('division.index') }}">Division</a></li>
                <li class="breadcrumb-item active">Edit</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->

    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">
            {!! Form::model($division, ['url' => route('division.update', $division->id),
                'method' => 'put' , 'id' => 'form_validation']) !!}
                @include('master.division._form')
            {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<!-- validator -->
<script src="{{ asset('gentelella/vendors/validator/validator.js') }}"></script>
@endsection

resources/views/master/division/index.blade.php
@extends('adminlte::page')

@section('title', 'Division - Manufacturing 4.0')

@section('content_header')
    <h1>Division</h1>
@stop

@section('content')
<div class="right_col" role="main">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-6 align-self-center">
        <h4 class="c-grey-900 mT-10 mB-30">Management Division</h4> </div>
        <div class="col-md-6 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">PPC</li>
                <li class="breadcrumb-item active">Division</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    
    @if(session()->has('flash_notification.message'))
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="body">
                @if(session()->get('flash_notification.level') == 'danger')
                <div style="background-color:red" class="alert alert-{{ session()->get('flash_notification.level') }} alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong><font color="white">{!! session()->get('flash_notification.message') !!}</font></strong>
                </div>
                @else
                <div class="alert alert-{{ session()->get('flash_notification.level') }} alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong><font color="white">{!! session()->get('flash_notification.message') !!}</font></strong>
                </div>
                @endif
            </div>
        </div>
    </div>
    @endif

    <div class="row">
        <div class="col-md-12">
            <div class="card card-default color-palette-box">
                <div class="card-body">
                    <div class="table-responsive">
                        {!! $dataTable->table(['class' => 'display nowrap table table-hover table-striped', 'width' => '100%']) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    {!! $dataTable->scripts() !!}
    <script> console.log('Hi!'); </script>
@stop