routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('welcome');
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' =>['auth','role:superadmin|ppc']],function(){
    Route::resource('user', 'mUserController');
    Route::resource('md', 'mManufactureDrawingController');

    Route::get('md_wp/wip/',[
        'as' => 'md_wip.wip',
        'uses' => 'mManufactureDrawingController@work_in_progress' 
    ]);

    Route::get('md_rl/rel',[
        'as' => 'md_rel.rel',
        'uses' => 'mManufactureDrawingController@released' 
    ]);

    Route::resource('is', 'mInspectionSheetController');

    Route::get('is_wp/wip',[
        'as' => 'is.wip',
        'uses' => 'mInspectionSheetController@work_in_progress' 
    ]);

    Route::get('is_rl/rel',[
        'as' => 'is.rel',
        'uses' => 'mInspectionSheetController@released' 
    ]);

    Route::resource('division', 'mDivisionController');
    Route::resource('position', 'mPositionController');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laratrust\Traits\LaratrustUserTrait;
use Illuminate\Support\Facades\Auth;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class User extends Authenticatable implements AuditableContract
{
    use LaratrustUserTrait;
    use Notifiable;
    use Auditable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'nip','division_id','position_id','email', 'password', 'path'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    // protected $casts = [
    //     'email_verified_at' => 'datetime',
    // ];

    public function division(){
        return $this->belongsTo('App\mDivision','division_id','id');
    }

    public function position(){
        return $this->belongsTo('App\mPosition','position_id','id');
    }
}

resources/views/master/user/_form.blade.php
<div class="row p-t-20">
<div class="col-md-2">
        <div class="form-group{{ $errors->has('nip') ? 'has-error': '' }} ">
            {!! Form::label('nip', 'NIP', ['class'=>'form-label']) !!}
            {!! Form::text('nip', null, ['class'=>'form-control', 'maxlength' => '9']) !!} 
            {!! $errors->first('nip', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('name') ? 'has-error': '' }} ">
            {!! Form::label('name', 'Nama', ['class'=>'form-label']) !!}
            {!! Form::text('name', null, ['class'=>'form-control']) !!} 
            {!! $errors->first('name', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('division_id') ? 'has-error': '' }} ">
            {!! Form::label('division_id', 'Division', ['class'=>'form-label']) !!}
            {!! Form::select('division_id', $div->pluck('division_name','id')->all(), null, [ 'class' => 'js-selectize form-control']) !!}
            {!! $errors->first('division_id', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
</div>
    <div class="row p-t-20">
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('position_id') ? 'has-error': '' }} ">
            {!! Form::label('position_id', 'Position', ['class'=>'form-label']) !!}
            {!! Form::select('position_id', $position->pluck('position_name','id')->all(), null, [ 'class' => 'form-control js-selectize','placeholder' => 'Pilih Position', 'id' => 'position_id']) !!}
            {!! $errors->first('position_id', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('email') ? 'has-error': '' }} ">
            {!! Form::label('email', 'Email', ['class'=>'form-label']) !!}
            {!! Form::text('email', null, ['class'=>'form-control']) !!} 
            {!! $errors->first('email', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('password') ? 'has-error': '' }} ">
            {!! Form::label('password', 'Password', ['class'=>'form-label']) !!}
            {!! Form::password('password', ['class'=>'form-control', 'id' => 'password']) !!} 
            {!! $errors->first('password', '<small class="text-danger">:message</small>') !!}
        </div>   
    </div>

    <div class="col-md-2">
        <div class="form-group{{ $errors->has('password_confirmation') ? 'has-error': '' }} ">
            {!! Form::label('password_confirmation', 'Confirm Password', ['class'=>'form-label']) !!}
            {!! Form::password('password_confirmation', ['class'=>'form-control']) !!} 
            {!! $errors->first('password_confirmation', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>

    <div class="col-md-2">
        <div class="form-group {{ $errors->has('role_id') ? 'has-error': '' }} ">
            {!! Form::label('role_id', 'Role User', ['class'=>'form-label']) !!}
            {!! Form::select('role_id[]', $list_role->pluck('display_name','id')->all(), null, [ 'class' => 'form-control multi-selectize', 'multiple'=>'multiple', 'placeholder' => 'Pilih Role', 'id' => 'role_id']) !!}
            {!! $errors->first('role_id', '<small class="text-danger">:message</small>') !!}
        </div>   
    </div>
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('id_card') ? 'has-error': '' }} ">
            {!! Form::label('id_card', 'ID Card', ['class'=>'form-label']) !!}
            {!! Form::text('id_card', null, ['class'=>'form-control']) !!} 
            {!! $errors->first('id_card', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group form-float{{ $errors->has('image_pf') ? 'has-error' : '' }}">
        {!! Form::label('image_pf','Foto Karyawan', ['class'=> 'form-label']) !!}
        {!! Form::file('image_pf'); !!}
        {!! $errors->first('image_pf', '<p class="error">:message</p>') !!}
        </div>
    </div>
</div>

{!! Form::submit ('Simpan',['class'=>'btn btn-primary m-b-10 m-l-5']) !!}

resources/views/master/user/_form_edit.blade.php
<div class="row p-t-20">
<div class="col-md-2">
        <div class="form-group{{ $errors->has('nip') ? 'has-error': '' }} ">
            {!! Form::label('nip', 'NIP', ['class'=>'form-label']) !!}
            {!! Form::text('nip', null, ['class'=>'form-control', 'maxlength' => '9']) !!} 
            {!! $errors->first('nip', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('name') ? 'has-error': '' }} ">
            {!! Form::label('name', 'Nama', ['class'=>'form-label']) !!}
            {!! Form::text('name', null, ['class'=>'form-control']) !!} 
            {!! $errors->first('name', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('plant_id') ? 'has-error': '' }} ">
            {!! Form::label('plant_id', 'Plant', ['class'=>'form-label']) !!}
            {!! Form::select('plant_id', $plant->pluck('plant_name','id')->all(), null, [ 'class' => 'js-selectize form-control']) !!}
            {!! $errors->first('plant_id', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('division_id') ? 'has-error': '' }} ">
            {!! Form::label('division_id', 'Division', ['class'=>'form-label']) !!}
            {!! Form::select('division_id', $division->pluck('division_name','id')->all(), null, [ 'class' => 'js-selectize form-control']) !!}
            {!! $errors->first('division_id', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
</div>
    <div class="row p-t-20">
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('position_id') ? 'has-error': '' }} ">
            {!! Form::label('position_id', 'Position', ['class'=>'form-label']) !!}
            {!! Form::select('position_id', $position->pluck('position_name','id')->all(), $user->pluck('position_id'), [ 'class' => 'form-control js-selectize','placeholder' => 'Pilih Position', 'id' => 'position_id']) !!}
            {!! $errors->first('position_id', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('email') ? 'has-error': '' }} ">
            {!! Form::label('email', 'Email', ['class'=>'form-label']) !!}
            {!! Form::text('email', null, ['class'=>'form-control']) !!} 
            {!! $errors->first('email', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
        <div class="col-md-2">
            <div class="form-group{{ $errors->has('password') ? 'has-error': '' }} ">
                {!! Form::label('password', 'Password', ['class'=>'form-label']) !!}
                {!! Form::password('password', ['class'=>'form-control', 'id' => 'password']) !!} 
                {!! $errors->first('password', '<small class="text-danger">:message</small>') !!}
            </div>   
        </div>
        <div class="col-md-2">
            <div class="form-group{{ $errors->has('password_confirmation') ? 'has-error': '' }} ">
                {!! Form::label('password_confirmation', 'Confirm Password', ['class'=>'form-label']) !!}
                {!! Form::password('password_confirmation', ['class'=>'form-control']) !!} 
                {!! $errors->first('password_confirmation', '<small class="text-danger">:message</small>') !!}
            </div>
        </div>

        <div class="col-md-2">
                <div class="form-group{{ $errors->has('role_id') ? 'has-error': '' }} ">
                    {!! Form::label('role_id', 'Role', ['class'=>'form-label']) !!}
                    {!! Form::select('role_id[]', $roles->pluck('display_name','id')->all(), $user_roles->pluck('id'), [ 'class' => 'form-control multi-selectize', 'multiple'=>'multiple', 'placeholder' => 'Pilih Role', 'id' => 'role_id']) !!}
                    {!! $errors->first('role_id', '<small class="text-danger">:message</small>') !!}
                </div>
            </div>
    <div class="col-md-2">
        <div class="form-group{{ $errors->has('id_card') ? 'has-error': '' }} ">
            {!! Form::label('id_card', 'ID Card', ['class'=>'form-label']) !!}
            {!! Form::text('id_card', null, ['class'=>'form-control']) !!} 
            {!! $errors->first('id_card', '<small class="text-danger">:message</small>') !!}
        </div>
    </div>
</div>

{!! Form::submit ('Simpan',['class'=>'btn btn-primary m-b-10 m-l-5']) !!}

resources/views/master/user/create.blade.php
@section('scripts')
<!-- validator -->
<script src="{{ asset('gentelella/vendors/validator/validator.js') }}"></script>
@endsection

@extends('adminlte::page')

@section('title', 'User - Manufacturing 4.0')

@section('content_header')
    <h1>USER</h1>
@stop

@section('content')
<div class="right_col" role="main">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-6 align-self-center">
        <h4 class="c-grey-900 mT-10 mB-30">Master User</h4> </div>
        <div class="col-md-6 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Master</li>
                <li class="breadcrumb-item active">User</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    
    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">
                {!! Form::open(['url' => route('user.store'),
                    'method' => 'post' ,'files' => 'true' , 'id' => 'form_validation']) !!}
                    @include('master.user._form')
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@stop

@section('css')
    <!-- <link rel="stylesheet" href="/css/admin_custom.css"> -->
@stop

@section('js')
    <script>
        $('.multi-selectize').selectize({
            plugins : ['remove_button'],
            maxItems : null,
            delimiter : ',',
            persist : true,
        });
    </script>
@endsection

resources/views/master/user/edit.blade.php
@extends('adminlte::page')

@section('title', 'User - Manufacturing 4.0')

@section('content_header')
    <h1>User</h1>
@stop

@section('content')
<div class="right_col" role="main">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-6 align-self-center">
        <h4 class="c-grey-900 mT-10 mB-30">Management User</h4> </div>
        <div class="col-md-6 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Master Data</li>
                <li class="breadcrumb-item">Document</li>
                <li class="breadcrumb-item"><a href="{{ route('user.index') }}">User</a></li>
                <li class="breadcrumb-item active">Edit</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->

    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">
            {!! Form::model($user, ['url' => route('user.update', $user->id),
                'method' => 'put' , 'id' => 'form_validation']) !!}
                @include('master.user._form_edit')
            {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<!-- validator -->
<script src="{{ asset('gentelella/vendors/validator/validator.js') }}"></script>
@endsection

@section('js')
    <script>
        $('.multi-selectize').selectize({
            plugins : ['remove_button'],
            maxItems : null,
            delimiter : ',',
            persist : true,
        });
    </script>
@endsection

resources/views/master/user/index.blade.php
@extends('adminlte::page')

@section('title', 'User - Manufacturing 4.0')

@section('content_header')
    <h1>USER</h1>
@stop

@section('content')
<div class="right_col" role="main">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-6 align-self-center">
        <h4 class="c-grey-900 mT-10 mB-30">Master User</h4> </div>
        <div class="col-md-6 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Master</li>
                <li class="breadcrumb-item active">User</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    @if(session()->has('flash_notification.message'))
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="body">
                @if(session()->get('flash_notification.level') == 'danger')
                <div style="background-color:red" class="alert alert-{{ session()->get('flash_notification.level') }} alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong><font color="white">{!! session()->get('flash_notification.message') !!}</font></strong>
                </div>
                @else
                <div class="alert alert-{{ session()->get('flash_notification.level') }} alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong><font color="white">{!! session()->get('flash_notification.message') !!}</font></strong>
                </div>
                @endif
            </div>
        </div>
    </div>
    @endif
    
    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">
                <div class="table-responsive">
                    {!! $dataTable->table(['class' => 'display nowrap table table-hover table-striped', 'width' => '100%']) !!}
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('css')
    <!-- <link rel="stylesheet" href="/css/admin_custom.css"> -->
@stop

@section('js')
    {!! $dataTable->scripts() !!}
    <script>
    <!-- <script> console.log('Hi!'); </script> -->
@stop